### ISSUE TITLE
RFE: Do not print a summary when the test directory is empty

### ISSUE THREAD

**Issue by jhradilek** [emender/emender#1]
When the **./test/** directory is empty, the **emend** command currently prints the following summary:

    ---------------------------------------------------------------------------
                                   :: Summary ::
    ---------------------------------------------------------------------------

      Executed Tests: 0
      Passed Tests:   0
      Failed Tests:   0
      Overall Result: FAIL

    ---------------------------------------------------------------------------
    Generated by Emender                            https://github.com/emender/

While it makes perfect sense to include such a summary in generated TXT, HTML, or XML reports, on the command line, I would prefer to see a brief, explanatory message. For example:

    No tests to run.

In addition, in generated reports, the overall status should be **N/A** or **Not available**.

The **emend** command should return **0** in this situation.

**Comment by tisnik** [comment]
Fixed.
