### ISSUE TITLE
Support for test waivers 

### ISSUE THREAD

**Issue by pmkovar** [emender/emender#12]
Similarly to what other test frameworks do, there should be a way for users to waive failed tests. Emender should be also able to remember the waivers, e.g. based on the changed content, so that users don't have to waive the same false positives again with each test run.

**Comment by jhradilek** [comment]
Thank you very much for taking the time to submit the request, Petr. While I agree that this would be a good functionality to have and fully support this idea, I don't think that Emender is the right component to provide it.

**Comment by pmkovar** [comment]
Cool. Feel free to move this issue to the right component.

**Comment by jhradilek** [comment]
Thank you, Petr.
