### ISSUE TITLE
Add a test for XML entities

### ISSUE THREAD

**Issue by soulcharmer** [emender/emender#14]
For Docbook content, it would be great to have a simple test that goes through .ent files and checks two uses cases:

1) defined entities that are not used in the text at all - reported as bugs

2) defined entities that are only used a few times - reported as warnings/info. The threshold could heuristically set depending on how big the whole book is, i.e. 3 for short books but as much as 10 for really long ones.

**Comment by jhradilek** [comment]
Thank you very much for taking the time to write this request, Tomas. This repository is, however, dedicated to the tool itself and does not include libraries or individual tests. I copied this request to the appropriate issue tracker and I am therefore closing this one as *invalid*.
