### ISSUE TITLE
RFE: Implement the --debug command line option

### ISSUE THREAD

**Issue by jhradilek** [emender/emender#15]
When implementing a new test, it is common practice to print debugging information to standard error output. Currently, emender itself does not support this feature and as a result, test authors use the following code snippet as a workaround:

``` lua
function TestRelease.printDebug(message)
    if TestRelease.debug ~= 0 then
        io.stderr:write("DEBUG: '" .. message .. "'\n\n")
    end
end
```

To enable this debugging mode, they take advantage of the `--X` command line option as follows:

```
emend --Xdebug=1
```

I think it would be much more user friendly if they could use a built-in function named `debug()` that would be similar to `warn()` and use it in their code as follows:

``` lua
debug("No language specified. Using '" .. TestRelease.language .. "'")
```

These debugging messages should be properly indented and displayed only when the `emend` command is executed with the `--debug` command line option:

```
emend --debug
```

**Comment by tisnik** [comment]
We'd need to use different name for debug() function because there's exist module with the same name and by defining new symbol 'debug', the old one (name of module) would be overrided.

**Comment by baruza** [comment]
so what about verbose or something like that?

**Comment by jhradilek** [comment]
I suggest `yap()`.<sup>1</sup>
___
<sup>1</sup> http://www.macmillandictionary.com/dictionary/american/yap_1

**Comment by baruza** [comment]
I like yap :)

**Comment by tisnik** [comment]
ok then :)

**Comment by tisnik** [comment]
It's been implemented and can be check by following two commands:

* ```emend test/TestDebug.lua```
* ```emend --debug test/TestDebug.lua```
