### ISSUE TITLE
RFE: Do not print a summary when the test directory does not exist

### ISSUE THREAD

**Issue by jhradilek** [emender/emender#2]
When no test is specified on the command line and the **./test/** directory does not exist, the **emend** command currently reports this directory as missing and prints a summary as usual:

    Test directory '/home/jhradilek/test' does not exist!
    ---------------------------------------------------------------------------
                                   :: Summary ::
    ---------------------------------------------------------------------------

      Executed Tests: 0
      Passed Tests:   0
      Failed Tests:   0
      Overall Result: FAIL

    ---------------------------------------------------------------------------
    Generated by Emender                            https://github.com/emender/

The **emend** command should report an error and return a non-zero value in this situation. The command should also fail to generate generate any reports if requested.

**Comment by tisnik** [comment]
It's already fixed:

$ ./emend
Test directory '/home/ptisnovsk/repos/emender/test' does not exist!
No tests to run.

$ echo $?
1
