### ISSUE TITLE
makefile issue: -e option of echo being echoed.

### ISSUE THREAD

**Issue by tylerkelly13** [emender/emender#22]
https://github.com/emender/emender/blob/defabba6fa5df7ef9f1776045f16f87a8d102532/Makefile#L64
echo on the line above is can result in:
```
**$ cat /usr/local/bin/emend**
-e #!/bin/bash
lua /usr/local/share/emender/emend "$@"
```
resulting in run error:
```
/usr/local/bin/emend: 1: /usr/local/bin/emend: -e: not found
```
Recommend replacing with ```printf```

**Comment by tisnik** [comment]
It's been fixed by you :+1: in #23 so let's close this issue.
