### ISSUE TITLE
Asterisks are not highlighted properly when the --color option is used

### ISSUE THREAD

**Issue by jhradilek** [emender/emender#4]
When the **emend** command is issued with the **-c** (or **--color**) command line option, it highlights any text enclosed in asterisks. If this text ends with an asterisk, however, the current version does not include it in the highlighted area. For example, consider the following string:

    Package **xorg-x11-drv-*** not found.

When used in a test function, the **emend** command displays it as follows:

> Package __xorg-x11-drv-</span>__* not found.

Note that the asterisk is not bold.

**Comment by tisnik** [comment]
Fixed.
