### ISSUE TITLE
RFE: Do no include the “Generated by” line in the command output

### ISSUE THREAD

**Issue by jhradilek** [emender/emender#5]
The latest development version of the **emend** command includes the “Generated by” line in the command's output, for example:

    ---------------------------------------------------------------------------
                                   :: Summary ::
    ---------------------------------------------------------------------------

      Executed Tests: 3
      Passed Tests:   1
      Failed Tests:   2
      Overall Result: FAIL

    ---------------------------------------------------------------------------
    Generated by Emender                            https://github.com/emender/

While it makes absolute sense to include this line in generated reports, I don't think it is necessary to see it every time you run the tool. The output should therefore look like this:

    ---------------------------------------------------------------------------
                                   :: Summary ::
    ---------------------------------------------------------------------------

      Executed Tests: 3
      Passed Tests:   1
      Failed Tests:   2
      Overall Result: FAIL

Note that there should be one empty line after “Overall Result”.

**Comment by tisnik** [comment]
Fixed.
