### ISSUE TITLE
The emend command fails with a traceback when the --list option is used

### ISSUE THREAD

**Issue by jhradilek** [emender/emender#7]
An attempt to run the **emend** command with the **-l** (or **--list**) command-line option causes the tool to terminate unexpectedly with the following error message:

    lua: cannot open /home/jhradilek/.local/share/emender/test/TestCheckPackages.lua: No such file or directory
    stack traceback:
            [C]: in function 'dofile'
            /home/jhradilek/.local/share/emender/src/core.lua:233: in function 'printTestInfo'
            /home/jhradilek/.local/share/emender/src/core.lua:539: in function 'performTestList'
            /home/jhradilek/.local/share/emender/emend:218: in function 'main'
            /home/jhradilek/.local/share/emender/emend:229: in main chunk
            [C]: ?

Note that */home/jhradilek/.local/share/emender/* mentioned on the first line is the installation directory, not the current working directory. The *TestCheckPackages.lua* file is, in fact, located in *./test/* and */home/jhradilek/.local/share/emender/test/* does not exist.

**Comment by tisnik** [comment]
Fixed.
