### ISSUE TITLE
RFE: Implement the --tags command-line option

### ISSUE THREAD

**Issue by jhradilek** [emender/emender#9]
Emender allows programmers to specify a number of tags in the test definition. The current version of the **emend** command, however, completely ignores these tags and does not take advantage of them. It would be useful if the command allowed the user to run only the tests with selected tags associated with them:

```
Usage: emend [-clsvDT] [-o FILE] [-t TAG...] [FILE...]
       emend -h|-V|-L

-t, --tags TAGS     run only tests with selected tags; replace TAGS with
                    a comma-separated list of tags
```

For example, the following command should run only the tests that have the _DocBook_ and _Release_ tags:

```
emend --tags DocBook,Release
```

Note that according to **emender**(3), tags are case sensitive.

**Comment by tisnik** [comment]
@jhradilek that RFE has been implemented. You can check it with the standard Emender installation:

* ```emend -t tagA```
* ```emend -t tagA,tagB```
* ```emend -t tagA -t tagB```

(there are special tests that use such tags)
